[package]
name = "primitive-archiver"
version = "0.1.0"
edition = "2024"

[dependencies.async-compression]
version = "0.4.18"
default-features = false
features = ["tokio", "deflate"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies]
bytes = "1.10.0"
